version: "3.8"
services:
  server:
    container_name: ${BACKEND_CONTAINER_NAME}
    build: ./app
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes: # ローカルとコンテナのパスをマウント
      - ./app:/app
      - /etc/localtime:/etc/localtime:ro # タイムゾーンを日本時刻に設定
#      - $HOME/.aws/:/root/.aws/ # localのaws credential情報をコンテナにコピー (ローカルのaws情報を参照する場合)
    working_dir: /app
    command: air -c .air.toml
    ports:
      - ${BACKEND_PORT}:3000
    security_opt:
      - seccomp:unconfined
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - BACKEND_CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_CREDENTIAL_USER=${AWS_CREDENTIAL_USER}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
      - AWS_S3_REGION=${AWS_S3_REGION}
      - AWS_CLOUD_FRONT_URL=${AWS_CLOUD_FRONT_URL}
      - JWT_KEY=${JWT_KEY}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定

  db:
    container_name: ${POSTGRES_HOST}
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - "TZ=Asia/Tokyo" # タイムゾーンを日本時刻に設定
    image: postgres:14.2
    volumes:
      - postgres-data:/var/lib/postgresql/data:delegated
      - ./postgres/db:/docker-entrypoint-initdb.d  #初期データ
    ports:
      - "5432:5432"

volumes:
  postgres-data: