CREATE TABLE todos
(
    id BIGSERIAL NOT NULL,
    title VARCHAR(50) NOT NULL,
    comment TEXT NOT NULL,
    user_id BIGSERIAL NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_users FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE
);

CREATE TRIGGER update_tri BEFORE UPDATE ON todos FOR EACH ROW EXECUTE PROCEDURE set_update_time();